volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jbagger/Inception/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jbagger/Inception/data/mariadb'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile # optional, the default is `Dockerfile`
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile # optional, the default is `Dockerfile`
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - inception
    restart: always
    env_file: .env
  
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile # optional, the default is `Dockerfile`
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
    env_file: .env