version: '3.5'

volumes:
  wordpress:
  mariadb:

networks:
  inception-network:

services:

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    expose:
      - "9000"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      depends_on:
        - mariadb

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"