# This is my guess at the commands to run to build the docker image
docker build -t nginx /requirements/nginx

# Here we run the container and list the contents of the root directory
docker run -it nginx
ls
apt upgrade
apt install nginx
exit