--------------------------------------------------------------------------------
	DOCKERFILE
--------------------------------------------------------------------------------

- specifies:
	- how the environment should be built
	- what should be run

- typical format:
	1. base image specification
	2. environment setup commands
	3. application installation commands
	4. exposed ports specification
	5. configuration setup commands
	6. startup commands and arguments

- Example how to configure an NGINX server from scratch:

	FROM debian:stable

	RUN apt-get update && apt-get install -y nginx
	RUN apt-get update && apt-get install -y openssl
	RUN mkdir -p /ssl
	RUN openssl genpkey -algorithm RSA -out /ssl/private.key
	RUN openssl req -new -x509 -days 365 -key /ssl/private.key -out /ssl/certificate.pem \
	-subj "/C=MA/ST=State/L=None/O=None/CN=None" 

	COPY conf /etc/nginx/nginx.conf
	COPY tools/launch.sh /launch.sh
	RUN chmod +x launch.sh

	CMD ["./launch.sh"]


INSTRUCTIONS:

- FROM		specifies the base image
- RUN		runs a command in the container (adds a new layer to the image)
- COPY		copies files from the host to the container
			COPY /path/to/host/file /path/to/container/file
- WORKDIR	specifies the working directory for the container (creates it if it doesnt exist)
- EXPOSE	specifies the port the container listens on
- CMD		specifies the command to run when the container starts